title: Avinash project 
description: ğŸŒ² test to see webpage discreption ğŸ
url: "https://avinashpudale.github.io/pinee"
markdown: kramdown
permalink: /:title
google_analytics: UA-144008567-1
youtube: https://www.youtube.com/
github:
  repository_url: https://github.com/AvinashPudale/pinee
  raw_content_url: https://raw.githubusercontent.com/AvinashPudale/pinee/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "test", "scripts", "firmware"]
include: ["_data"]
